<?php
/**
 * ItemCommentApi
 * PHP version 5
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace swagger_client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use swagger_client\ApiException;
use swagger_client\Configuration;
use swagger_client\HeaderSelector;
use swagger_client\ObjectSerializer;

/**
 * ItemCommentApi Class Doc Comment
 *
 * @category Class
 * @package  swagger_client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemCommentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation itemCommentListGet
     *
     * 评论列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws swagger_client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \swagger_client\Model\ItemCommentItemCommentInlineResponse200
     */
    public function itemCommentListGet($open_id, $access_token, $count, $item_id, $cursor = null)
    {
        list($response) = $this->itemCommentListGetWithHttpInfo($open_id, $access_token, $count, $item_id, $cursor);
        return $response;
    }

    /**
     * Operation itemCommentListGetWithHttpInfo
     *
     * 评论列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws swagger_client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \swagger_client\Model\ItemCommentItemCommentInlineResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function itemCommentListGetWithHttpInfo($open_id, $access_token, $count, $item_id, $cursor = null)
    {
        $returnType = '\swagger_client\Model\ItemCommentItemCommentInlineResponse200';
        $request = $this->itemCommentListGetRequest($open_id, $access_token, $count, $item_id, $cursor);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\swagger_client\Model\ItemCommentItemCommentInlineResponse200',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemCommentListGetAsync
     *
     * 评论列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemCommentListGetAsync($open_id, $access_token, $count, $item_id, $cursor = null)
    {
        return $this->itemCommentListGetAsyncWithHttpInfo($open_id, $access_token, $count, $item_id, $cursor)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemCommentListGetAsyncWithHttpInfo
     *
     * 评论列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemCommentListGetAsyncWithHttpInfo($open_id, $access_token, $count, $item_id, $cursor = null)
    {
        $returnType = '\swagger_client\Model\ItemCommentItemCommentInlineResponse200';
        $request = $this->itemCommentListGetRequest($open_id, $access_token, $count, $item_id, $cursor);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemCommentListGet'
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemCommentListGetRequest($open_id, $access_token, $count, $item_id, $cursor = null)
    {
        // verify the required parameter 'open_id' is set
        if ($open_id === null || (is_array($open_id) && count($open_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_id when calling itemCommentListGet'
            );
        }
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling itemCommentListGet'
            );
        }
        // verify the required parameter 'count' is set
        if ($count === null || (is_array($count) && count($count) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $count when calling itemCommentListGet'
            );
        }
        // verify the required parameter 'item_id' is set
        if ($item_id === null || (is_array($item_id) && count($item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_id when calling itemCommentListGet'
            );
        }

        $resourcePath = '/item/comment/list/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($open_id !== null) {
            $queryParams['open_id'] = ObjectSerializer::toQueryValue($open_id);
        }
        // query params
        if ($access_token !== null) {
            $queryParams['access_token'] = ObjectSerializer::toQueryValue($access_token);
        }
        // query params
        if ($cursor !== null) {
            $queryParams['cursor'] = ObjectSerializer::toQueryValue($cursor);
        }
        // query params
        if ($count !== null) {
            $queryParams['count'] = ObjectSerializer::toQueryValue($count);
        }
        // query params
        if ($item_id !== null) {
            $queryParams['item_id'] = ObjectSerializer::toQueryValue($item_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation itemCommentReplyListGet
     *
     * 评论回复列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  string $comment_id 评论id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws swagger_client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \swagger_client\Model\ItemCommentItemCommentInlineResponse200
     */
    public function itemCommentReplyListGet($open_id, $access_token, $count, $item_id, $comment_id, $cursor = null)
    {
        list($response) = $this->itemCommentReplyListGetWithHttpInfo($open_id, $access_token, $count, $item_id, $comment_id, $cursor);
        return $response;
    }

    /**
     * Operation itemCommentReplyListGetWithHttpInfo
     *
     * 评论回复列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  string $comment_id 评论id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws swagger_client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \swagger_client\Model\ItemCommentItemCommentInlineResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function itemCommentReplyListGetWithHttpInfo($open_id, $access_token, $count, $item_id, $comment_id, $cursor = null)
    {
        $returnType = '\swagger_client\Model\ItemCommentItemCommentInlineResponse200';
        $request = $this->itemCommentReplyListGetRequest($open_id, $access_token, $count, $item_id, $comment_id, $cursor);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\swagger_client\Model\ItemCommentItemCommentInlineResponse200',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemCommentReplyListGetAsync
     *
     * 评论回复列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  string $comment_id 评论id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemCommentReplyListGetAsync($open_id, $access_token, $count, $item_id, $comment_id, $cursor = null)
    {
        return $this->itemCommentReplyListGetAsyncWithHttpInfo($open_id, $access_token, $count, $item_id, $comment_id, $cursor)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemCommentReplyListGetAsyncWithHttpInfo
     *
     * 评论回复列表
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  string $comment_id 评论id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemCommentReplyListGetAsyncWithHttpInfo($open_id, $access_token, $count, $item_id, $comment_id, $cursor = null)
    {
        $returnType = '\swagger_client\Model\ItemCommentItemCommentInlineResponse200';
        $request = $this->itemCommentReplyListGetRequest($open_id, $access_token, $count, $item_id, $comment_id, $cursor);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemCommentReplyListGet'
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  int $count 每页数量 (required)
     * @param  string $item_id 视频id (required)
     * @param  string $comment_id 评论id (required)
     * @param  int $cursor 分页游标, 第一页请求cursor是0, response中会返回下一页请求用到的cursor, 同时response还会返回has_more来表明是否有更多的数据。 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemCommentReplyListGetRequest($open_id, $access_token, $count, $item_id, $comment_id, $cursor = null)
    {
        // verify the required parameter 'open_id' is set
        if ($open_id === null || (is_array($open_id) && count($open_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_id when calling itemCommentReplyListGet'
            );
        }
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling itemCommentReplyListGet'
            );
        }
        // verify the required parameter 'count' is set
        if ($count === null || (is_array($count) && count($count) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $count when calling itemCommentReplyListGet'
            );
        }
        // verify the required parameter 'item_id' is set
        if ($item_id === null || (is_array($item_id) && count($item_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $item_id when calling itemCommentReplyListGet'
            );
        }
        // verify the required parameter 'comment_id' is set
        if ($comment_id === null || (is_array($comment_id) && count($comment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $comment_id when calling itemCommentReplyListGet'
            );
        }

        $resourcePath = '/item/comment/reply/list/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($open_id !== null) {
            $queryParams['open_id'] = ObjectSerializer::toQueryValue($open_id);
        }
        // query params
        if ($access_token !== null) {
            $queryParams['access_token'] = ObjectSerializer::toQueryValue($access_token);
        }
        // query params
        if ($cursor !== null) {
            $queryParams['cursor'] = ObjectSerializer::toQueryValue($cursor);
        }
        // query params
        if ($count !== null) {
            $queryParams['count'] = ObjectSerializer::toQueryValue($count);
        }
        // query params
        if ($item_id !== null) {
            $queryParams['item_id'] = ObjectSerializer::toQueryValue($item_id);
        }
        // query params
        if ($comment_id !== null) {
            $queryParams['comment_id'] = ObjectSerializer::toQueryValue($comment_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation itemCommentReplyPost
     *
     * 回复视频评论
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  \swagger_client\Model\ItemCommentItemCommentBody $body body (optional)
     *
     * @throws swagger_client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \swagger_client\Model\ItemCommentItemCommentInlineResponse2001
     */
    public function itemCommentReplyPost($open_id, $access_token, $body = null)
    {
        list($response) = $this->itemCommentReplyPostWithHttpInfo($open_id, $access_token, $body);
        return $response;
    }

    /**
     * Operation itemCommentReplyPostWithHttpInfo
     *
     * 回复视频评论
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  \swagger_client\Model\ItemCommentItemCommentBody $body (optional)
     *
     * @throws swagger_client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \swagger_client\Model\ItemCommentItemCommentInlineResponse2001, HTTP status code, HTTP response headers (array of strings)
     */
    public function itemCommentReplyPostWithHttpInfo($open_id, $access_token, $body = null)
    {
        $returnType = '\swagger_client\Model\ItemCommentItemCommentInlineResponse2001';
        $request = $this->itemCommentReplyPostRequest($open_id, $access_token, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\swagger_client\Model\ItemCommentItemCommentInlineResponse2001',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation itemCommentReplyPostAsync
     *
     * 回复视频评论
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  \swagger_client\Model\ItemCommentItemCommentBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemCommentReplyPostAsync($open_id, $access_token, $body = null)
    {
        return $this->itemCommentReplyPostAsyncWithHttpInfo($open_id, $access_token, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation itemCommentReplyPostAsyncWithHttpInfo
     *
     * 回复视频评论
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  \swagger_client\Model\ItemCommentItemCommentBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function itemCommentReplyPostAsyncWithHttpInfo($open_id, $access_token, $body = null)
    {
        $returnType = '\swagger_client\Model\ItemCommentItemCommentInlineResponse2001';
        $request = $this->itemCommentReplyPostRequest($open_id, $access_token, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'itemCommentReplyPost'
     *
     * @param  string $open_id 通过/oauth/access_token/获取，用户唯一标志 (required)
     * @param  string $access_token 调用/oauth/access_token/生成的token，此token需要用户授权。 (required)
     * @param  \swagger_client\Model\ItemCommentItemCommentBody $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function itemCommentReplyPostRequest($open_id, $access_token, $body = null)
    {
        // verify the required parameter 'open_id' is set
        if ($open_id === null || (is_array($open_id) && count($open_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $open_id when calling itemCommentReplyPost'
            );
        }
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling itemCommentReplyPost'
            );
        }

        $resourcePath = '/item/comment/reply/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($open_id !== null) {
            $queryParams['open_id'] = ObjectSerializer::toQueryValue($open_id);
        }
        // query params
        if ($access_token !== null) {
            $queryParams['access_token'] = ObjectSerializer::toQueryValue($access_token);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
